baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Commons Conservancy'

# https://gohugo.io/content-management/markdown-attributes/
[markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
    block = true
    title = true
